### ISSUE TITLE
login

### ISSUE THREAD

**Issue by Liambeguin** [Dronolab/meta-drono#11]
Do we need a passwd on the root user ? 
and do we need another user than root ?

**Comment by rolland-fx** [comment]
Another than root : not really. Only known or drono-made software will run on the OS. There is only question about some software which cannot run as root.

Root passwd : yes, we need it (for security reason, but also because it's a requirement in some situations).

**Comment by Liambeguin** [comment]
OK, I'm having some issues with automating this... 
for now, we'll  have to add a passwd manually when needed.
