### ISSUE TITLE
remove ipv6

### ISSUE THREAD

**Issue by Liambeguin** [Dronolab/meta-drono#26]
As far as I know, IPv6 is not required !

**Comment by rolland-fx** [comment]
not needed indeed

François-Xavier Rolland

Étudiant au baccalauréat en Génie électrique - ÉTS, Montréal
Responsable électronique - électrique - Télécommunication Dronolab
<http://dronolab.com> ÉTS

(514) 433-5812 // rolland.fx@gmail.com //
francois-xavier.rolland.1x@etsmtl.net
[image: Dronolab] <http://dronolab.com>

2015-07-08 22:02 GMT-04:00 Liam BEGUIN <notifications@github.com>:

**Comment by Liambeguin** [comment]
IPv6 is no longer built within the kernel but I still need to du something about this message : 
```
...
Switching root
Failed to insert module 'ipv6'

Welcome to Dronolab Distribution 0.1 (master)!
...
```
