### ISSUE TITLE
can we have a serial console un the usb port ? 

### ISSUE THREAD

**Issue by Liambeguin** [Dronolab/meta-drono#4]

**Comment by rolland-fx** [comment]
If only needed for login (cannot be use for boot debug) 

In /ect/inittab, add 
U0:23:respawn:/sbin/getty -L ttyUSB0 115200 vt100

if needed for boot debug, need to compile the Kernel with special config :
https://www.raspberrypi.org/forums/viewtopic.php?f=71&t=48683

**Comment by Liambeguin** [comment]
since the uUSB connector is not wired this is no longer of interest ! 

![raspi_microusb](https://cloud.githubusercontent.com/assets/3811160/8762628/75816692-2d4c-11e5-9fc9-b7e44f431cd5.png)
